on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: acts_as_reactable
          # Should breaking changes before 1.0.0 produce minor bumps?
          bump-minor-pre-major: true
          version-file: "lib/acts_as_reactable/version.rb"
      # Setup ruby if a release was created
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby # latest stable cruby
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        if: ${{ steps.release.outputs.release_created }}
      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}
